services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - CHAT_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=gpt-oss:20b
    # Ensure the special hostname works on Linux (Docker Desktop on macOS/Windows already provides it)
    extra_hosts:
      - "host.docker.internal:host-gateway"
