# syntax=docker/dockerfile:1

# ──────────────────────────────────────────────────────────────
# Stage 1 – deps
#   Install ALL dependencies (production + dev) with a locked
#   manifest.  devDependencies are needed by the Next.js compiler
#   in the builder stage.  NODE_ENV=development is set explicitly
#   so that npm ci always installs devDependencies regardless of
#   any inherited environment variable.
# ──────────────────────────────────────────────────────────────
FROM node:22-slim AS deps

WORKDIR /app

# Declare development environment so npm ci includes devDependencies
ENV NODE_ENV=development

# Copy only the manifests first – this layer is re-used on cache hit
COPY src/web/package.json src/web/package-lock.json ./

# Install deps and immediately purge the npm cache so it does not
# bloat the layer that is carried forward into the builder stage.
RUN npm ci --no-audit --no-fund \
 && npm cache clean --force

# ──────────────────────────────────────────────────────────────
# Stage 2 – builder
#   Compile the Next.js application.
#   output: "standalone" in next.config.ts produces a self-contained
#   server bundle under .next/standalone that we copy into the runner.
# ──────────────────────────────────────────────────────────────
FROM node:22-slim AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=production

# Bring in the installed modules from the deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the full application source
COPY src/web .

# Build the Next.js app (runs `next build --turbopack` via the script)
RUN npm run build

# ──────────────────────────────────────────────────────────────
# Stage 3 – runner
#   Minimal runtime image: only the standalone server bundle,
#   static assets and public files are copied in.
# ──────────────────────────────────────────────────────────────
FROM node:22-slim AS runner

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    HOSTNAME=0.0.0.0 \
    PORT=3000

# Create a non-root system user/group with pinned IDs (1001:1001) for
# reproducibility across builds and environments.  The base node:22-slim
# image already owns UID/GID 1000 ("node"), so 1001 avoids any clash.
# Pre-create the Next.js cache directory and set ownership — combined
# into a single RUN to minimise the number of image layers.
RUN groupadd --system --gid 1001 nextjs \
 && useradd --system --uid 1001 --gid nextjs --no-create-home nextjs \
 && mkdir -p /app/.next/cache \
 && chown -R nextjs:nextjs /app

# Copy the minimal standalone server produced by Next.js
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone ./

# Copy the compiled static assets (CSS, JS chunks, etc.)
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static

# Copy public assets (images, fonts, robots.txt, etc.)
COPY --from=builder --chown=nextjs:nextjs /app/public ./public

EXPOSE 3000

USER nextjs

# Liveness / readiness probe target.  curl is not present in node:22-slim,
# so the check is implemented with Node's built-in http module.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/', (r) => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"

# server.js is the entry-point generated by Next.js standalone output
CMD ["node", "server.js"]