apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contoso-air
  namespace: contoso-air
  labels:
    app.kubernetes.io/name: contoso-air
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: contoso-air.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contoso-air
                port:
                  name: http
