apiVersion: v1
kind: ServiceAccount
metadata:
  name: contoso-air-sa
  namespace: team-blue
  labels:
    app.kubernetes.io/name: contoso-air
    app.kubernetes.io/managed-by: containerization-assist
  annotations:
    azure.workload.identity/client-id: "dd6cfbb9-10ad-45db-af99-bdd313244e3b"